version: '3.8'
services:
  bubblebot:
    image: gcr.io/certain-mission-399804/bubblebot
    ports:
      - "3000:3000"
    volumes:
      - ./auth:/usr/src/app/.auth
      - ./cache:/usr/src/app/.cache
    environment:
      - REDIS_URL=rediss://default:dce4434ca00845d09c4c6e2fe9bd5a9e@gusc1-precious-cicada-30864.upstash.io:30864
    restart: always
